'use client';

import { FooterTag } from '~/presentation/common/components';
import '~/presentation/common/styles/global.css';

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='pt-br'>
      <head>
        <meta charSet='utf-8' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.png' />
      </head>
      <body className='bg-gray1'>
        {children}
        <FooterTag />
      </body>
    </html>
  );
}
